# Initialize zsh
source <(fzf --zsh)

# Initialize mise
eval "$(~/.local/bin/mise activate zsh)"

# Initialize zoxide
eval "$(zoxide init zsh)"

# Initialize starship
eval "$(starship init zsh)"


# Added by Devin
export PATH="/Users/koralle/.codeium/windsurf/bin:$PATH"
